name: basic
on:
  push:
    tags: [ "v*" ]
    branches: [ main ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    name: build-dialoguss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: true
          go-version: 1.18.x
      - uses: actions/checkout@v2
      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2